### ISSUE TITLE
React 19 - Each child in a list should have a unique "key" prop.

### ISSUE THREAD

**Issue by Arkellys** [react-grid-layout/react-grid-layout#2045]
### Describe the bug

When trying `react-grid-layout` with React 19 (beta), I get the following error:

```shell
Warning: Each child in a list should have a unique "key" prop.

Check the top-level render call using <Fragment>. It was passed a child from ReactGridLayout. See https://react.dev/link/warning-keys for more information.
    at GridItem (http://localhost:3000/static/js/app.bundle.js:82024:5)
    at div
    at ReactGridLayout (http://localhost:3000/static/js/app.bundle.js:82620:5)
    at ResponsiveReactGridLayout (http://localhost:3000/static/js/app.bundle.js:83614:5)
    at WidthProvider (
   ...
```

### Your Example Website or App

https://codesandbox.io/p/sandbox/react-grid-layout-d5v98m

### Steps to Reproduce the Bug or Issue

Open the sandbox then open the console. I believe the bug is present on all grids, whether they have blocks or not.

### Expected behavior

There should not be `key` error.

### react-grid-layout library version

1.4.1

### Operating System Version

Windows

### Browser

Chrome

### Additional context

If I'm not wrong, the fix is just adding a `key` [here](https://github.com/react-grid-layout/react-grid-layout/blob/04a778264b056a024334d33d17305a57970ccc40/lib/ReactGridLayout.jsx#L637). I'm not sure why there is no error on React 18.

**Comment by Arkellys** [comment]
Solved on `19.0.0-rc-bf3a29d097-20240603`. So it was a problem with the beta version.
I'm still wondering why we don't always get the error though, I can't see `key` on `GridItem`.
